name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'yarn'

      - name: Enable Corepack (for Yarn Berry support)
        run: corepack enable

      # Yarn Berry면 --immutable, Yarn v1이면 --frozen-lockfile 사용
      - name: Install deps (Yarn)
        run: |
          yarn --version
          yarn install --immutable || yarn install --frozen-lockfile

      - name: Build (Next.js static export)
        env:
          NODE_ENV: production
        run: yarn build

      - name: Move _next under basePath
        run: |
          BASE=oreurock-home
          mkdir -p "out/$BASE/_next"
          rsync -a "out/_next/" "out/$BASE/_next/"

      - name: Add .nojekyll
        run: touch ./out/.nojekyll

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./out

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4